# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

env:
  NODE_ENV: production

jobs:
  build:

    runs-on: ubuntu-latest
    environment: github-pages

    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: 16.x
        cache: 'pnpm'
    - name: Setup PNPM
      uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.32.3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
    - run: pnpm install
    - run: pnpm build
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

